# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cyclography of Things
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This project tackles processes, methods and techniques used throughout history of culture and science
  in an attempt to shed light on "life cycle" of things. Strategies employed to allow voiceless objects
  narrate their biography are ranging from literary genres like "it narratives" all the way through to "hard"
  technologies like RFID - and are being examined by this research project, as well as their similarities and 
  differences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
